curso/urls.py
from django.urls import path

from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sysif/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aluno/', include('aluno.urls')),
    path('turma/', include('turma.urls')),
    path('professor/', include('professor.urls')),
    path('disciplina/', include('disciplina.urls')),
    path('curso/', include('curso.urls')),
]

curso/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from curso.forms import FormCadastrarCurso

# Durval - Classe curso
class Curso(models.Model):
    nome_curso = models.CharField('Nome', max_length=250)
    codigo_curso = models.CharField('Código curso', max_length=100)
    descricao = models.CharField('Descrição', max_length=500)
    
    def __str__(self):
        return self.nome_curso
    
    class Meta:
        verbose_name = 'Curso'
        ordering = ['nome_curso']

    # Luis metodo cadastrar Curso

    def cadastrar(request):

        context = {}
        context['is_not_cadastred'] = True

        if request.method == 'POST':
            form = FormCadastrarCurso(request.POST)

            #verifica se o preenchimento foi valido
            if form.is_valid():
                context['is_valid'] = True

                #recebe os valores digitados nos campos do form
                nome_curso  = request.POST['nome_curso']
                codigo_curso = request.POST['codigo_curso']
                descricao = request.POST['descricao']

                #cadastra o curso

                cadastra_curso = Curso(nome_curso = nome_curso, 
                codigo_curso = codigo_curso, 
                descricao = descricao)

                cadastra_curso.save()

                form = FormCadastrarCurso()
                context['is_not_cadastred'] = False

        else:
            form = FormCadastrarCurso()   
        
        context['form'] = form

        return context     

    #Luis Metodo de editar curso, nesse metodo, alem do request, ele recebe também o id do curso
    def editar(request, id):
        
        curso = get_object_or_404(Curso, id=id)
        context = {}
        context['is_not_edited'] = True
        
        if request.method == 'POST':
            form = FormCadastrarCurso(request.POST)

            #verifica se o preenchimento foi valido
            if form.is_valid():
                context['is_valid'] = True

                #recebe os valores digitados nos campos do form

                nome_curso  = request.POST['nome_curso']
                codigo_curso = request.POST['codigo_curso']
                descricao = request.POST['descricao']

                #editar curso
                edita_curso = Curso.objects.filter(id=id)
                edita_curso.update(
                    nome_curso=nome_curso, 
                    codigo_curso=codigo_curso, 
                    descricao=descricao
                )

                form = FormCadastrarCurso()
                context['is_not_edited'] = False

        #Se o formulario ja tiver sido preenchido anteriormente, ele irá retornar o formulario com os dados anteriores para edição

        else:

            form = FormCadastrarCurso()

            form.initial['nome_curso'] = curso.nome_curso
            form.initial['codigo_curso'] = curso.codigo_curso
            form.initial['descricao'] = curso.descricao

        context['form'] = form
        context['id'] = id
                    
        return (context)


    #LUIS metodo de deletar curso:

    def deletar(request, id):

        curso = get_object_or_404(Curso, id=id)
        curso.delete()

curso/forms.py
from django import forms

#Durval - Abaixo eu crio um formulario para curso
class FormCadastrarCurso(forms.Form):
    
    nome_curso = forms.CharField(label='Nome do curso', widget=forms.TextInput)
    codigo_curso = forms.CharField(label='Codigo do curso', widget=forms.TextInput)
    descricao = forms.CharField(label='Descrição do curso', widget=forms.Textarea)
        

curso/views.py
from django.shortcuts import render
from curso.models import Curso
from aluno.models import Aluno
from professor.models import Professor
from disciplina.models import Disciplina

def cadastrar(request):
   
    context = Curso.cadastrar(request) #Luis - funcao sendo chamada do models 'Curso' para cadastrar curso

    return render(request, 'cadastrar_curso.html', context)

def editar(request, id):
   
    context = Curso.editar(request, id) #Luis - funcao sendo chamada do models 'curso' para editar curso
        
    return render(request, 'editar_curso.html', context)

def deletar(request, id):
   
    context = {}
    
    curso = Curso.objects.get(id = id)
    aluno = Aluno.objects.filter(id_curso = id)
    professor = Professor.objects.filter(id_curso = id)
    disciplina = Disciplina.objects.filter(id_curso = id)

    valid = True 

    mensagem = 'O curso está alocado em '

    if aluno:
        mensagem = mensagem + 'aluno, '
        context['is_valid'] = False
        valid = False

    if valid == False:
        if disciplina:
            mensagem = mensagem + 'disciplina,'
            context['is_valid'] = False
            valid = False
    if valid == False:
        if professor:
            mensagem = mensagem + 'professor,'
            context['is_valid'] = False
            valid = False

    mensagem = mensagem + 'portanto não pode ser deletado'

    context['mensagem'] = mensagem

    if valid == True:
        context['is_valid'] = True
        curso.delete()




    return render(request, 'deletar_curso.html', context)

#durval - tela de CRUD de curso
def dashboard(request):
    
     cursos_cadastrados = Curso.objects.all()
    
     context ={
        'cursos_cadastrados': cursos_cadastrados,
     }

     return render(request, 'curso_dashboard.html', context)

curso/templates/cadastrar_curso.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Curso{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Cadastro realizado.</h3>
            </div>
        </div>
    
        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'curso:dashboard' %}">Retornar para dashboard</a></div>
  

    {% endif %}

    {% if is_not_cadastred == True %}
    <div class="form-title box">
        <h3>Cadastro de curso</h3>
    </div>
    
    <form action="{% url 'curso:cadastrar' %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Cadastrar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

curso/templates/curso_dashboard.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Curso{% endblock %}

{% block content %} 

    <div class="info-div">
        <a href="{% url 'curso:cadastrar' %}" class="cadastrar">
            <img src="../../static/img/cadastro_simbolo.png" alt="" width="30px"> 
            CADASTRAR
        </a>
    </div>
    
    <table class="table table-striped table-sm">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Codigo</th>
          <th scope="col">Descrição</th>
          <th scope="col">Editar</th>
          <th scope="col">Deletar</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cursos_cadastrados %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
          <td>{{item.nome_curso}}</td>
          <td>{{item.codigo_curso}}</td>
          <td>{{item.descricao}}</td>

          <td><a class="btn btn-sm btn-warning" href="{% url 'curso:editar' item.id %}">Editar</a></td>
          <td><a class="btn btn-sm btn-danger" href="{% url 'curso:deletar' item.id %}" onclick="return confirm('Deseja deletar esse curso?')">Deletar</a></td>

        {% endfor %}
        </tr>
    
    </tbody>
    </table>
{% endblock %}

curso/templates/deletar_curso.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Curso{% endblock %}

{% block content %} 

{%if is_valid == True%}

<div class="info-div">
    <div class="mensagem">
        <img src="../../static/img/sucess_message.png" alt="" width="50px">
        <h3>Curso deletado.</h3>
    </div>
</div>
{%endif%}

{% if is_valid == False %}
<div class="info-div">
    <div class="mensagem-red">
        <img src="../../static/img/error_message.png" alt="" width="50px">
        <h3>{{mensagem}}</h3>
    </div>
</div>
{% endif %}
<div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'curso:dashboard' %}">Retornar para dashboard</a></div>



{% endblock %}

curso/templates/editar_curso.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Curso{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Edição realizada.</h3>
            </div>
        </div>
    
        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'curso:dashboard' %}">Retornar para dashboard</a></div>

    {% endif %}

    {% if is_not_edited == True %}
    <div class="form-title box">
        <h3>Edição de curso</h3>
    </div>
    
    <form action="{% url 'curso:editar' id %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Editar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}