main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

sysif/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aluno/', include('aluno.urls')),
    path('turma/', include('turma.urls')),
    path('professor/', include('professor.urls')),
    path('disciplina/', include('disciplina.urls')),
    path('curso/', include('curso.urls')),
]

turma/urls.py
from django.urls import path
from . import views

app_name = 'turma'

urlpatterns = [
    path('', views.dashboard_turma, name='dashboard'),
    path('cadastrar/', views.cadastrar_turma, name='cadastrar'),
    path('editar/<int:id>', views.editar_turma, name='editar'),
    path('deletar/<int:id>', views.deletar_turma, name='deletar'),
    path('avaliacao/', views.dashboard_avaliacao, name='dashboardAvaliacao'),
    path('lancarAvaliacao/', views.lancar_avaliacao, name='lancarAvaliacao'),
    path('editarAvaliacao/<int:id>', views.editar_avaliacao, name='editarAvaliacao'),
    path('deletarAvaliacao/<int:id>', views.deletar_avaliacao, name='deletarAvaliacao'),
    path('alocarAluno/', views.alocar_aluno, name = 'alocarAluno'),
    path('verAlunos/<int:id>', views.ver_alunos, name='verAlunos'),
    path('retirarAlunos/<int:id>, <int:idt>', views.retirar_alunos, name ='retirarAlunos'),
]

turma/models.py
from django.db import models
from aluno.models import Aluno
from professor.models import Professor #Durval - importando classe professor do modulo professor
from disciplina.models import Disciplina #Durval - importando classe disciplina do modulo disciplina
from django.shortcuts import get_object_or_404

#Durval - Classe turma, possui chave estrangeira de professor e disciplina
class Turma(models.Model):
    id_professor = models.ForeignKey(Professor, on_delete=models.DO_NOTHING) #Durval - chave estrangeira da tabela professor
    id_disciplina = models.ForeignKey(Disciplina, on_delete=models.DO_NOTHING) #Durval - chave estrangeira da tabela disciplina
    cod_turma = models.CharField('Codigo turma', max_length=250)
    semestre = models.IntegerField('Semestre')
    horario = models.TimeField('Horario')
    dia_semana = models.IntegerField('Dia da semana')
    
    def __str__(self):
        return self.cod_turma
    
    class Meta:
        verbose_name = 'Turma'
        ordering = ['cod_turma']
    # Durval - função para cadastrar turma, ela recebe o request da view e retorna um context para ser utilizado no template da view
    def cadastrar(request):
        
         from .forms import FormCadastrarTurma #Durval - por algum motivo n consigo importar no topo do codigo, fica dando erro
         context = {}
         context['is_not_cadastred'] = True
        
         if request.method == 'POST':
             form = FormCadastrarTurma(request.POST)
             
             if form.is_valid():
                 context['is_valid'] = True
                 
                 cod_turma = request.POST['cod_turma']
                 semestre = request.POST['semestre']
                 horario = request.POST['horario']
                 dia_semana = request.POST['dia_semana']
                 id_professor = request.POST['id_professor']
                 professor = Professor.objects.get(id=id_professor)
                 id_disciplina = request.POST['id_disciplina']
                 disciplina = Disciplina.objects.get(id=id_disciplina)
         
                 cadastra_turma = Turma(cod_turma=cod_turma,
                                     semestre=semestre,
                                     horario=horario,
                                     dia_semana=dia_semana,
                                     id_professor=professor,
                                     id_disciplina=disciplina
                                     )
                 
                 cadastra_turma.save()
                 
                 form = FormCadastrarTurma()
                 context['is_not_cadastred'] = False
                 
         else:
             form = FormCadastrarTurma()
             
         context['form'] = form
         
         return context
    
    #Durval - função para editar, ela recebe o request da view e o id da turma, e retorna um context para ser utilizado no template da view
    def editar(request, id):
        
        from .forms import FormCadastrarTurma #Durval - por algum motivo n consigo importar no topo do codigo, fica dando erro
        
        turma = get_object_or_404(Turma,id=id)
        context = {}
        context['is_not_edited'] = True
        
        if request.method == 'POST':
             form = FormCadastrarTurma(request.POST)
             
             if form.is_valid():
                 context['is_valid'] = True
                 
                 cod_turma = request.POST['cod_turma']
                 semestre = request.POST['semestre']
                 horario = request.POST['horario']
                 dia_semana = request.POST['dia_semana']
                 id_professor = request.POST['id_professor']
                 professor = Professor.objects.get(id=id_professor)
                 id_disciplina = request.POST['id_disciplina']
                 disciplina = Disciplina.objects.get(id=id_disciplina)
         
                 edita_turma = Turma.objects.filter(id=id)
                 edita_turma.update(cod_turma=cod_turma,
                                     semestre=semestre,
                                     horario=horario,
                                     dia_semana=dia_semana,
                                     id_professor=professor,
                                     id_disciplina=disciplina
                                     )
                 
                 form = FormCadastrarTurma()
                 context['is_not_edited'] = False
                
        else:
            form = FormCadastrarTurma()
            
            form.initial['cod_turma'] = turma.cod_turma
            form.initial['semestre'] = turma.semestre
            form.initial['horario'] = turma.horario
            form.initial['dia_semana'] = turma.dia_semana
            form.initial['id_professor'] = turma.id_professor
            form.initial['id_disciplina'] = turma.id_disciplina
            
        context['form'] = form
        context['id'] = id
                
        return (context)

    #Durval - função para deletar turma, ela recebe o request da view e o id da turma, não retorna nada
    def deletar(request, id):
        
        turma = get_object_or_404(Turma,id=id)
        turma.delete()
        
        
#-----------------------------------------------------------------------------------------------

#Durval - Classe avaliação, possui chave estrangeira de turma e aluno
class Avaliacao(models.Model):
    id_turma = models.ForeignKey(Turma, on_delete=models.DO_NOTHING) #Durval - chave estrangeira da tabela turma
    id_aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE) #Durval - chave estrangeira da tabela aluno
    nota1 = models.FloatField('Nota 1')
    nota2 = models.FloatField('Nota 2')
    provaFinal = models.FloatField('Prova final')
    frequencia = models.IntegerField('Frequência')
    
    def __str__(self):
        return self
    
    class Meta:
        verbose_name = 'Avaliaçõe'
        ordering = ['id_aluno']
        
    # Durval - função para lancar avakiacao, ela recebe o request da view e retorna um context para ser utilizado no template da view
    def lancar(request):
        
         from .forms import FormCadastrarAvaliacao #Durval - por algum motivo n consigo importar no topo do codigo, fica dando erro
         
         context = {}
         context['is_not_cadastred'] = True
        
         if request.method == 'POST':
             form = FormCadastrarAvaliacao(request.POST)
             
             if form.is_valid():

                 id_turma = request.POST['id_turma']
                 id_aluno = request.POST['id_aluno']
                 aluno = Aluno.objects.get(id = id_aluno)
                 turma_aluno = TurmaAluno.objects.filter(id_turma_id = id_turma)

                 for i in turma_aluno:
                    if i.id_aluno == aluno:
                        
                        context['is_valid'] = True
                 
                        nota1 = request.POST['nota1']
                        nota2 = request.POST['nota1']
                        provaFinal = request.POST['provaFinal']
                        frequencia = request.POST['frequencia']
                        id_turma = request.POST['id_turma']
                        turma = Turma.objects.get(id=id_turma)
                        id_aluno = request.POST['id_aluno']
                        aluno = Aluno.objects.get(id=id_aluno)
                
                        cadastra_avaliacao = Avaliacao(nota1=nota1,
                                            nota2=nota2,
                                            provaFinal=provaFinal,
                                            frequencia=frequencia,
                                            id_turma=turma,
                                            id_aluno=aluno
                                            )
                        
                        cadastra_avaliacao.save()
                        break
                    else:
                        context['is_valid'] = False
                 
                 form = FormCadastrarAvaliacao()
                 context['is_not_cadastred'] = False
                 
         else:
             form = FormCadastrarAvaliacao()
             
         context['form'] = form
         
         return context
    
    #Durval - função para editar, ela recebe o request da view e o id da avalicao, e retorna um context para ser utilizado no template da view
    def editar(request, id):
        
        from .forms import FormCadastrarAvaliacao #Durval - por algum motivo n consigo importar no topo do codigo, fica dando erro
        avaliacao = get_object_or_404(Avaliacao,id=id)
        context = {}
        context['is_not_edited'] = True
        
        if request.method == 'POST':
             form = FormCadastrarAvaliacao(request.POST)
             
             if form.is_valid():
                 context['is_valid'] = True
                 
                 nota1 = request.POST['nota1']
                 nota2 = request.POST['nota1']
                 provaFinal = request.POST['provaFinal']
                 frequencia = request.POST['frequencia']
                 id_turma = request.POST['id_turma']
                 turma = Turma.objects.get(id=id_turma)
                 id_aluno = request.POST['id_aluno']
                 aluno = Aluno.objects.get(id=id_aluno)
         
                 edita_avaliacao= Avaliacao.objects.filter(id=id)
                 edita_avaliacao.update(nota1=nota1,
                                     nota2=nota2,
                                     provaFinal=provaFinal,
                                     frequencia=frequencia,
                                     id_turma=turma,
                                     id_aluno=aluno
                                     )
                 
                 form = FormCadastrarAvaliacao()
                 context['is_not_edited'] = False
                
        else:

turma/forms.py
from django import forms
from curso.models import Curso
from professor.models import Professor
from disciplina.models import Disciplina
from aluno.models import Aluno
from .models import Turma

class FormCadastrarTurma(forms.Form):
    
    #Durval = abaixo eu preencho uma lista de opções de professores com todos os possiveis professores cadastrados
    all_professores = Professor.objects.all().values_list('id', 'nome')
    
    professores_choice = [('', '')]
    
    for i in all_professores:
        professores_choice.append(i)
    
    #Durval = abaixo eu preencho uma lista de opções de disciplinaas com todas as possiveis disciplinas cadastradas
    all_disciplina = Disciplina.objects.all().values_list('id', 'nome_disciplina')
    
    disciplina_choices = [('', '')]
    
    for i in all_disciplina:
        disciplina_choices.append(i)
        
    #Durval - abaixo eu crio os campos do meu formulario
    id_professor = forms.ChoiceField(label='Professor da turma', choices=professores_choice, widget=forms.Select()) #Durval - esse é um campo onde o usuario irá escolher um professor para atrelar a turma
    id_disciplina = forms.ChoiceField(label='Disciplina da turma', choices=disciplina_choices, widget=forms.Select()) #Durval - esse é um campo onde o usuario irá escolher uma disciplina para atrelar a turma 
    cod_turma = forms.CharField(label='Codigo da turma', widget=forms.TextInput)
    semestre = forms.IntegerField(label='Semeste', widget=forms.NumberInput)
    horario = forms.TimeField()
    dia_semana = forms.IntegerField(label='Dia da semana', widget=forms.NumberInput)
    
    
class FormCadastrarAvaliacao(forms.Form):
    
    #Durval = abaixo eu preencho uma lista de opções de turmas com todas as possiveis turmas cadastradas
    all_turmas = Turma.objects.all().values_list('id', 'cod_turma')
    
    turmas_choice = [('', '')]
    
    for i in all_turmas:
        turmas_choice.append(i)
    
    #Durval = abaixo eu preencho uma lista de opções de alunos com todos os possiveis alunos cadastrados
    all_alunos = Aluno.objects.all().values_list('id', 'nome')
    
    alunos_choice = [('', '')]
    
    for i in all_alunos:
        alunos_choice.append(i)
    
    #Durval - abaixo eu crio os campos do meu formulario
    id_turma = forms.ChoiceField(label='Turma', choices=turmas_choice, widget=forms.Select()) #Durval - esse é um campo onde o usuario irá escolher uma turma para atrelar a avaliação 
    id_aluno = forms.ChoiceField(label='Aluno', choices=alunos_choice, widget=forms.Select()) #Durval - esse é um campo onde o usuario irá escolher um aluno para atrelar a avaliação 
    nota1 = forms.FloatField(label='Nota 1', widget=forms.NumberInput)
    nota2 = forms.FloatField(label='Nota 2', widget=forms.NumberInput)
    provaFinal = forms.FloatField(label='Prova final', widget=forms.NumberInput)
    frequencia = forms.IntegerField(label='Frequencia', widget=forms.NumberInput)

class FormAlocarAluno(forms.Form):

    all_alunos = Aluno.objects.all().values_list('id', 'nome')

    alunos_choice = [('', '')]

    for i in all_alunos:
        alunos_choice.append(i)

    all_turmas = Turma.objects.all().values_list('id','cod_turma')

    turma_choice = [('', '')]

    for i in all_turmas:
        turma_choice.append(i)

    id_turma = forms.ChoiceField(label='Turma', choices=turma_choice, widget=forms.Select())
    id_aluno = forms.ChoiceField(label='Aluno', choices=alunos_choice, widget=forms.Select())

    

turma/views.py
from django.shortcuts import render
from turma.models import Turma, Avaliacao, TurmaAluno
from aluno.models import Aluno

# views para turma
def cadastrar_turma(request):
   
    context = Turma.cadastrar(request) #Durval - aqui eu chamo a função de cadastro de turma, a ordem de negócio se encontra lá
        
    return render(request, 'cadastrar_turma.html', context)

def editar_turma(request, id):
   
    context = Turma.editar(request, id) #Durval - aqui eu chamo a função de editar turma, a ordem de negócio se encontra lá
        
    return render(request, 'editar_turma.html', context)

def deletar_turma(request, id):
   
    context = Turma.deletar(request, id) #Durval - aqui eu chamo a função de deletar turma, a ordem de negócio se encontra lá
        
    return render(request, 'deletar_turma.html', context)

def dashboard_turma(request):
    
     turmas_cadastradas = Turma.objects.all()
    
     context ={
        'turmas_cadastradas': turmas_cadastradas,
     }

     return render(request, 'turma_dashboard.html', context)
 
#----------------------------------------------------------

# views para avaliacao
def lancar_avaliacao(request):
   
    context = Avaliacao.lancar(request) #Durval - aqui eu chamo a função de cadastro de avaliacao, a ordem de negócio se encontra lá
        
    return render(request, 'lancar_avaliacao.html', context)

def editar_avaliacao(request, id):
   
    context = Avaliacao.editar(request, id) #Durval - aqui eu chamo a função de editar avaliacao, a ordem de negócio se encontra lá
        
    return render(request, 'editar_avaliacao.html', context)

def deletar_avaliacao(request, id):
   
    context = Avaliacao.deletar(request, id) #Durval - aqui eu chamo a função de deletar avaliacao, a ordem de negócio se encontra lá
        
    return render(request, 'deletar_avaliacao.html', context)

def dashboard_avaliacao(request):
    
     avaliacoes_lancadas = Avaliacao.objects.all()
    
     context ={
        'avaliacoes_lancadas': avaliacoes_lancadas,
     }

     return render(request, 'avaliacao_dashboard.html', context)


def alocar_aluno(request):
    context = TurmaAluno.alocar_aluno(request)

    return render(request, 'alocar_aluno.html', context)

def ver_alunos(request, id):

    turma = Turma.objects.get(id = id)

    alunos_alocados = TurmaAluno.objects.filter(id_turma = id)

    context = {
        'alunos_alocados': alunos_alocados,
    }

    context ['turma'] = turma

    return render(request, 'ver_alunos.html', context)

def retirar_alunos(request, id, idt):

    context = TurmaAluno.retirar_alunos(request, id, idt)

    return render(request,'retirar_alunos.html', context)

    
 

turma/templates/alocar_aluno.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Turma{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid == True%}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Aluno alocado!</h3>
            </div>
        </div>
        
        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboard' %}">Retornar para dashboard</a></div>
    
    {% endif %}

    {% if is_valid == False%}
    <div class="info-div-red">
        <div class="mensagem-red">
            <img src="../../static/img/error_message.png" alt="" width="90px">
            <h3>Aluno já alocado!</h3>
        </div>
    </div>
    
    <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboard' %}">Retornar para dashboard</a></div>

     {% endif %}

    {% if is_not_cadastred == True %}
    <div class="form-title box">
        <h3>Alocação de aluno</h3>
    </div>
    
    <form action="{% url 'turma:alocarAluno' %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Alocar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

turma/templates/avaliacao_dashboard.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Avaliação{% endblock %}

{% block content %} 

    <div class="info-div">
        <a href="{% url 'turma:lancarAvaliacao' %}" class="cadastrar">
            <img src="../../static/img/cadastro_simbolo.png" alt="" width="30px"> 
            CADASTRAR
        </a>
    </div>
    
    <table class="table table-striped table-sm">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Aluno</th>
          <th scope="col">Turma</th>
          <th scope="col">Nota 1</th>
          <th scope="col">Nota 2</th>
          <th scope="col">Prova final</th>
          <th scope="col">Frequencia</th>
          <th scope="col">Editar</th>
          <th scope="col">Deletar</th>
        </tr>
      </thead>
      <tbody>
        {% for item in avaliacoes_lancadas %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
          <td>{{item.id_aluno.nome}}</td>
          <td>{{item.id_turma}}</td>
          <td>{{item.nota1}}</td>
          <td>{{item.nota2}}</td>
          <td>{{item.provaFinal}}</td>
          <td>{{item.frequencia}}</td>
          
          <td><a class="btn btn-sm btn-warning" href="{% url 'turma:editarAvaliacao' item.id %}">Editar</a></td>
          <td><a class="btn btn-sm btn-danger" href="{% url 'turma:deletarAvaliacao' item.id %}" onclick="return confirm('Deseja deletar essa avaliação?')">Deletar</a></td>

        {% endfor %}
        </tr>
    
    </tbody>
    </table>
{% endblock %}

turma/templates/cadastrar_turma.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Turma{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

   

    {% if is_valid %}
        <div class="info-div">
            <div href="{% url 'turma:cadastrar' %}" class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Cadastro realizado.</h3>
            </div>
        </div>
        
        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboard' %}">Retornar para dashboard</a></div>
    
    {% endif %}

    {% if is_not_cadastred == True %}
    <div class="form-title box">
        <h3>Cadastro de turma</h3>
    </div>
    
    <form action="{% url 'turma:cadastrar' %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Cadastrar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

turma/templates/deletar_avaliacao.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Avaliação{% endblock %}

{% block content %} 
    
<div class="info-div">
    <div class="mensagem">
        <img src="../../static/img/sucess_message.png" alt="" width="50px">
        <h3>Avaliacao deletada.</h3>
    </div>
</div>

<div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboardAvaliacao' %}">Retornar para dashboard</a></div>

{% endblock %}

turma/templates/deletar_turma.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Turma{% endblock %}

{% block content %} 
    
<div class="info-div">
    <div class="mensagem">
        <img src="../../static/img/sucess_message.png" alt="" width="50px">
        <h3>Turma deletada.</h3>
    </div>
</div>

 <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboard' %}">Retornar para dashboard</a></div>

{% endblock %}

turma/templates/editar_avaliacao.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Avaliação{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Edição realizada.</h3>
            </div>
        </div>

        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboardAvaliacao' %}">Retornar para dashboard</a></div>

    {% endif %}

    {% if is_not_edited == True %}
    <div class="form-title box">
        <h3>Edição de Avaliação</h3>
    </div>
    
    <form action="{% url 'turma:editarAvaliacao' id %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Editar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

turma/templates/editar_turma.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Turma{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Edição realizada.</h3>
            </div>
        </div>

         <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboard' %}">Retornar para dashboard</a></div>

    {% endif %}

    {% if is_not_edited == True %}
    <div class="form-title box">
        <h3>Edição de turma</h3>
    </div>
    
    <form action="{% url 'turma:editar' id %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Editar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

turma/templates/lancar_avaliacao.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Avaliação{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid == True %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Lançamento realizado.</h3>
            </div>
        </div>
    
    <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboardAvaliacao' %}">Retornar para dashboard</a></div>
    
    {% endif %}  
        
    {% if is_valid == False %}
        <div class="info-div">
            <div class="mensagem-red">
                <img src="../../static/img/error_message.png" alt="" width="50px">
            <h3>O aluno não está alocado na turma selecionada </h3>
        </div>
    </div>

    <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboardAvaliacao' %}">Retornar para dashboard</a></div>
    {% endif %}
            
    
    {% if is_not_cadastred == True %}
    <div class="form-title box">
        <h3>Lançamento da Avaliação</h3>
    </div>
    
    <form action="{% url 'turma:lancarAvaliacao' %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Lançar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

turma/templates/retirar_alunos.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Retirar Aluno{% endblock %}

{% block content %} 
    
<div class="info-div">
    <div class="mensagem">
        <img src="../../static/img/sucess_message.png" alt="" width="50px">
        <h3>Aluno retirado!</h3>
    </div>
</div>

<div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'turma:dashboard' %}">Retornar para dashboard</a></div>

{% endblock %}

turma/templates/turma_dashboard.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Turma{% endblock %}

{% block content %} 

    <div class="info-div">
        <a href="{% url 'turma:cadastrar' %}" class="cadastrar">
            <img src="../../static/img/cadastro_simbolo.png" alt="" width="30px"> 
            CADASTRAR
        </a>

        <a href="{% url 'turma:alocarAluno' %}" class="cadastrar">
          <img src="../../static/img/cadastro_simbolo.png" alt="" width="30px"> 
          ALOCAR ALUNO
      </a>
    </div>

    
    <table class="table table-striped table-sm">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Código da turma</th>
          <th scope="col">Semestre</th>
          <th scope="col">Horário</th>
          <th scope="col">Dia da Semana</th>
          <th scope="col">Professor</th>
          <th scope="col">Disciplina</th>
          <th scope="col">Editar</th>
          <th scope="col">Deletar</th>
          <th scope="col">Ver</th>
        </tr>
      </thead>
      <tbody>
        {% for item in turmas_cadastradas %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
          <td>{{item.cod_turma}}</td>
          <td>{{item.semestre}}</td>
          <td>{{item.horario}}</td>
          <td>{{item.dia_semana}}</td>
          <td>{{item.id_professor}}</td>
          <td>{{item.id_disciplina.nome_disciplina}}</td>
          
          <td><a class="btn btn-sm btn-warning" href="{% url 'turma:editar' item.id %}">Editar</a></td>
          
          <td><a class="btn btn-sm btn-danger" href="{% url 'turma:deletar' item.id %}" onclick="return confirm('Deseja deletar essa turma?')">Deletar</a></td>
         
          <td><a class="btn btn-sm btn-primary" href="{% url 'turma:verAlunos' item.id %}">Ver</a></td>

        {% endfor %}
        </tr>
    
    </tbody>
    </table>
{% endblock %}

turma/templates/ver_alunos.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Alunos da Turma{% endblock %}

{% block content %} 

    <div class="info-div">
        <div class="form-title box">
            <h3> {{turma.cod_turma}}</h3>
           
        </div>

    </div>

    
    <table class="table table-striped table-sm">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Matricula</th>
          <th scope="col">Situacao</th>
          <th scope="col">Retirar</th>
        </tr>
      </thead>
      <tbody>
        {% for item in alunos_alocados %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
          <td>{{item.id_aluno.nome}}</td>
          <td>{{item.id_aluno.matricula}}</td>
          <td>{{item.id_aluno.situacao}}</td>

        <td><a class="btn btn-sm btn-danger" href="{% url 'turma:retirarAlunos' item.id_aluno.id item.id_turma.id %}" onclick="return confirm('Deseja retirar esse aluno da turma?')">Retirar</a></td>

        {% endfor %}
        </tr>
    
    </tbody>
    </table>
{% endblock %}