main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

professor/urls.py
from django.urls import path

from . import views

app_name = 'professor'

urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
    
]

sysif/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aluno/', include('aluno.urls')),
    path('turma/', include('turma.urls')),
    path('professor/', include('professor.urls')),
    path('disciplina/', include('disciplina.urls')),
    path('curso/', include('curso.urls')),
]

professor/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from curso.models import Curso # Durval - importando classe Curso do modulo curso
from professor.forms import FormCadastrarProfessor

# classe pessoa, super classe com as subclasses professor e aluno
class Pessoa(models.Model):
    nome = models.CharField('Nome', max_length=100)
    endereco = models.CharField('Endereço', max_length=250)
    telefone = models.CharField('Telefone', max_length=250)
    
    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name = 'Pessoa'
        ordering = ['nome']

    def cadastrar():
        
        return 0
    
    def editar():
        
        return 0
    
    def deletar():
        
        return 0
#Durval - subclasse professor, herda de pessoa
class Professor(Pessoa):
    id_curso = models.ForeignKey(Curso, on_delete=models.CASCADE) #Durval - passando a chave estangeira da classe (tabela) curso
    cod_professor = models.CharField('Codigo', max_length=250)
    titulacaoMax = models.CharField('Titulação Máxima', max_length=250)
    
    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name = 'Professore'
        ordering = ['nome']
        
     #LUIS - criando o metodo cadastrar professor

    def cadastrar(request):
        
        context={}
        context['is_not_cadastred'] = True
        
        if request.method == 'POST':
            
            form = FormCadastrarProfessor(request.POST)
            
            #verifica se o preenchimento foi valido
            if form.is_valid():
                context['is_valid'] = True
                
                #recebe os valores digitados no form
                nome = request.POST['nome']
                cod_professor = request.POST['cod_professor']
                titulacaoMax = request.POST['titulacaoMax']
                endereco = request.POST['endereco']
                telefone = request.POST['telefone']
                id_curso = request.POST['id_curso']

                curso = Curso.objects.get(id = id_curso)
                
                #cadastrando professor
                cadastra_professor = Professor(nome=nome, 
                        cod_professor=cod_professor, 
                        titulacaoMax=titulacaoMax, 
                        endereco=endereco, 
                        telefone=telefone, 
                        id_curso= curso)
                
                cadastra_professor.save()
                
                form = FormCadastrarProfessor()
                
                context['is_not_cadastred'] = False
                
        else:
            form = FormCadastrarProfessor()   
            
        context['form'] = form
        
        return context   
        
    #LUIS - Criando o metodo de editar professor
    def editar(request, id):
        professor = get_object_or_404(Professor, id=id)
        context = {}
        context['is_not_edited'] = True
        
        if request.method == 'POST':
            form = FormCadastrarProfessor(request.POST)
            #verifica se o preenchimento foi valido
            if form.is_valid():
                
                context['is_valid'] = True 
                
            #recebe os valores digitados no form
                nome = request.POST['nome']
                cod_professor = request.POST['cod_professor']
                titulacaoMax = request.POST['titulacaoMax']
                endereco = request.POST['endereco']
                telefone = request.POST['telefone']
                id_curso = request.POST['id_curso']
                
                #editando curso
                edita_professor = Professor.objects.filter(id=id)
                edita_professor.update(nome=nome, 
                            cod_professor=cod_professor, 
                            titulacaoMax=titulacaoMax, 
                            endereco=endereco, 
                            telefone=telefone, 
                            id_curso=id_curso)
                
                form = FormCadastrarProfessor()
                
                context['is_not_edited'] = False
        else:
            form = FormCadastrarProfessor()
            
            #se o formulario ja foi preenchido antes, ele irá retornar todas as respostas preenchidas e pronto para serem substituidas
            form.initial['nome'] = professor.nome
            form.initial['cod_professor'] = professor.cod_professor
            form.initial['titulacaoMax'] = professor.titulacaoMax
            form.initial['endereco'] = professor.endereco
            form.initial['telefone'] = professor.telefone
            form.initial['id_curso'] = professor.id_curso
            
        context['form'] = form
        context['id'] = id
                    
        return (context)
        
    #LUIS - Função para deletar professores

professor/forms.py
from django import forms
from curso.models import Curso

class FormCadastrarProfessor(forms.Form):
    
    #Durval = abaixo eu preencho uma lista de opções de curso com todos os possiveis cursos cadastrados
    all_cursos = Curso.objects.all().values_list('id', 'nome_curso')
    
    cursos_choice = [('', '')]
    
    for i in all_cursos:
        cursos_choice.append(i)
    
    nome = forms.CharField(label='Nome do Professor', widget=forms.TextInput)
    cod_professor = forms.CharField(label='Código do professor', widget=forms.TextInput)
    titulacaoMax = forms.CharField(label='Titulação máxima', widget=forms.TextInput)
    endereco = forms.CharField(label='Endereço do Professor', widget=forms.TextInput)
    telefone = forms.CharField(label='Telefone do Professor', widget=forms.TextInput)
    id_curso = forms.ChoiceField(label='Curso do Professor', choices=cursos_choice, widget=forms.Select()) #Durval - esse é um campo onde o usuario irá escolher um curso para atrelar ao professor 

professor/views.py
from django.shortcuts import render

from professor.models import Professor
from turma.models import Turma

def cadastrar(request):
   
    context = Professor.cadastrar(request) #Luis - funcao sendo chamada do models 'professor' para cadastrar professor
        
    return render(request, 'cadastrar_professor.html', context)

def editar(request, id):
   
    context = Professor.editar(request, id) #Luis - funcao sendo chamada do models 'professor' para editar professor
        
    return render(request, 'editar_professor.html', context)

def deletar(request, id):
   
    context = {}

    professor = Professor.objects.get(id = id)
    turma = Turma.objects.filter(id_professor_id = id)
    if turma:
        context['is_valid'] = True
    else:
        context['is_valid'] = False
        professor.delete()

        
    return render(request, 'deletar_professor.html', context)

def dashboard(request):
    
     professores_cadastrados = Professor.objects.all()
    
     context ={
        'professores_cadastrados': professores_cadastrados,
     }

     return render(request, 'professor_dashboard.html', context)

professor/templates/cadastrar_professor.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Professor{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Cadastro realizado.</h3>
            </div>
        </div>
     
        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'professor:dashboard' %}">Retornar para dashboard</a></div>

    {% endif %}

    {% if is_not_cadastred == True %}
    <div class="form-title box">
        <h3>Cadastro de Professor</h3>
    </div>
    
    <form action="{% url 'professor:cadastrar' %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Cadastrar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

professor/templates/deletar_professor.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Professor{% endblock %}

{% block content %} 

{%if is_valid == False %}
<div class="info-div">
    <div class="mensagem">
        <img src="../../static/img/sucess_message.png" alt="" width="50px">
        <h3>Professor deletado.</h3>
    </div>
</div>

{%endif%}

{% if is_valid == True %}
<div class="info-div">
    <div class="mensagem-red">
        <img src="../../static/img/error_message.png" alt="" width="50px">
        <h3>O professor está alocado em uma turma</h3>
    </div>
</div>
{% endif %}

<div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'professor:dashboard' %}">Retornar para dashboard</a></div>

{% endblock %}

professor/templates/editar_professor.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Professor{% endblock %}

{% block content %} 
    
    {% if form.errors %}
        <div class="mensage">
            {{ forms.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
        <div class="info-div">
            <div class="mensagem">
                <img src="../../static/img/sucess_message.png" alt="" width="50px">
                <h3>Edição realizada.</h3>
            </div>
        </div>
   
        <div class="margin-auto"> <a class="btn btn-sm btn-primary" href="{% url 'professor:dashboard' %}">Retornar para dashboard</a></div>

    {% endif %}

    {% if is_not_edited == True %}
    <div class="form-title box">
        <h3>Edição de Professor</h3>
    </div>
    
    <form action="{% url 'professor:editar' id %}" method="post">
            {% csrf_token %}

            {{ form|bootstrap }} <span></span> 
        <div class="button-div">
            <button type="submit" class="button-input" > Editar</button>
        </div>
    </form>
    {% endif %}
{% endblock %}

professor/templates/professor_dashboard.html
{% extends 'base.html' %} 

{% load static %}
{% load bootstrap %}

{% block title %}Professor{% endblock %}

{% block content %} 

    <div class="info-div">
        <a href="{% url 'professor:cadastrar' %}" class="cadastrar">
            <img src="../../static/img/cadastro_simbolo.png" alt="" width="30px"> 
            CADASTRAR
        </a>
    </div>
    
    <table class="table table-striped table-sm">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Código</th>
          <th scope="col">Titulção Máxima</th>
          <th scope="col">Endereço</th>
          <th scope="col">Telefone</th>
          <th scope="col">Curso</th>
          <th scope="col">Editar</th>
          <th scope="col">Deletar</th>
        </tr>
      </thead>
      <tbody>
        {% for item in professores_cadastrados %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
          <td>{{item.nome}}</td>
          <td>{{item.cod_professor}}</td>
          <td>{{item.titulacaoMax}}</td>
          <td>{{item.endereco}}</td>
          <td>{{item.telefone}}</td>
          <td>{{item.id_curso}}</td>
          
          <td><a class="btn btn-sm btn-warning" href="{% url 'professor:editar' item.id %}">Editar</a></td>
          <td><a class="btn btn-sm btn-danger" href="{% url 'professor:deletar' item.id %}" onclick="return confirm('Deseja deletar esse professor?')">Deletar</a></td>

        {% endfor %}
        </tr>
    
    </tbody>
    </table>
{% endblock %}