aluno/urls.py
from django.urls import path
from . import views

app_name = 'aluno'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar_aluno, name='cadastrar'),
    path('editar/<int:id>', views.editar_aluno, name='editar'),
    path('deletar/<int:id>', views.deletar_aluno, name='deletar'),
]

curso/urls.py
from django.urls import path

from . import views

app_name = 'curso'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

professor/urls.py
from django.urls import path

from . import views

app_name = 'professor'

urlpatterns = [

    path('', views.dashboard, name='dashboard'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
    
]

sysif/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('aluno/', include('aluno.urls')),
    path('turma/', include('turma.urls')),
    path('professor/', include('professor.urls')),
    path('disciplina/', include('disciplina.urls')),
    path('curso/', include('curso.urls')),
]

turma/urls.py
from django.urls import path
from . import views

app_name = 'turma'

urlpatterns = [
    path('', views.dashboard_turma, name='dashboard'),
    path('cadastrar/', views.cadastrar_turma, name='cadastrar'),
    path('editar/<int:id>', views.editar_turma, name='editar'),
    path('deletar/<int:id>', views.deletar_turma, name='deletar'),
    path('avaliacao/', views.dashboard_avaliacao, name='dashboardAvaliacao'),
    path('lancarAvaliacao/', views.lancar_avaliacao, name='lancarAvaliacao'),
    path('editarAvaliacao/<int:id>', views.editar_avaliacao, name='editarAvaliacao'),
    path('deletarAvaliacao/<int:id>', views.deletar_avaliacao, name='deletarAvaliacao'),
    path('alocarAluno/', views.alocar_aluno, name = 'alocarAluno'),
    path('verAlunos/<int:id>', views.ver_alunos, name='verAlunos'),
    path('retirarAlunos/<int:id>, <int:idt>', views.retirar_alunos, name ='retirarAlunos'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    
    return render(request, 'home.html')

main/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-light bg-light shadow">
    <div class="container-fluid">
        <a href="{% url 'main:home' %}" class="navbar-brand">
            <img src="../../static/img/logo_home.png" alt="" width="50px">
            <span class="navbar-brand mb-0 h1">SysiF</span>
        </a>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
  
  <div class="modal true" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header">
            <img src="../../static/img/logo_home.png" alt="" width="50px">
          <h5 class="modal-title" id="exampleModalLabel"> SysiF</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
  
          <ul class="list-group">
            <a href="{% url 'aluno:dashboard'%}">  <li class="list-group-item"> <img src="../../static/img/aluno_dashboard.png" alt="" width="25px"> Aluno </li>  </a>
            <a href="{% url 'professor:dashboard'%}">  <li class="list-group-item"> <img src="../../static/img/prof_dashboard.png" alt="" width="25px"> Professor</li>  </a>
            <a href="{% url 'curso:dashboard'%}">  <li class="list-group-item"> <img src="../../static/img/curso_dashboard.png" alt="" width="25px"> Curso</li>  </a>
            <a href="{% url 'turma:dashboard'%}">  <li class="list-group-item"> <img src="../../static/img/turma_dashboard.png" alt="" width="25px"> Turma</li>  </a>
            <a href="{% url 'disciplina:dashboard'%}">  <li class="list-group-item">  <img src="../../static/img/disci_dashboard.png" alt="" width="25px"> Disciplina</li>  </a>
            <a href="{% url 'turma:dashboardAvaliacao'%}">  <li class="list-group-item">  <img src="../../static/img/avali_dashboard.png" alt="" width="25px">Avaliação</li>  </a>
          </ul>
  
        </div>

      </div>
    </div>
  </div>
  